steps:
- name: 'docker.io/library/python:3.8'
  entrypoint: /bin/sh
  # Run pip install and pytest in the same build step
  # (pip packages won't be preserved in future steps!)
  args: [-c, 'pip install -r requirements.txt', '&&', 'pytest']
  dir: 'gcp-function'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'prisma-trello-card', '--trigger-http', '--runtime', 'python38', '--entry-point', 'prisma_trello_card']
  dir: 'function/dir/from/repo/root'